steps:
  - id: Download Web Dependencies
    dir: web
    name: "gcr.io/cloud-builders/yarn"
    args: ["install", " --frozen-lockfile"]
  - id: Build Web Assets
    dir: web
    name: "gcr.io/cloud-builders/yarn"
    args: ["build"]
  - name: gcr.io/cloud-builders/gsutil
    dir: web
    args: [
        "-m", # multi-thread
        "rsync",
        "-r", # recursive
        "-c", # compare checksums
        "-d", # delete extra files
        "./build", # from
        "${_WEB_DEPLOY_BUCKET}", # to
      ]

options:
  logging: CLOUD_LOGGING_ONLY
