runtime: python310

entrypoint: gunicorn --bind :$PORT --worker-class uvicorn.workers.UvicornWorker api.main:app

# these paths rely on the bundle-deploy-dir.sh script
handlers:
  # serve the api
  - url: /api.*
    script: auto
    secure: always
    redirect_http_response_code: 301

  # serve any request with a file extension
  - url: /(.*\..+)
    static_files: web/build/\1
    upload: web/build/(.*\..+)$
    secure: always
    redirect_http_response_code: 301

  # and serve everything else from the index file
  - url: /.*
    static_files: web/build/index.html
    upload: web/build/index.html
    secure: always
    redirect_http_response_code: 301
