runtime: python310

entrypoint: gunicorn --bind :$PORT --worker-class uvicorn.workers.UvicornWorker api.main:app

# these paths rely on the bundle-deploy-dir.sh script
handlers:
  - url: /
    static_files: build/index.html
    upload: web/build/index.html
    secure: always
    redirect_http_response_code: 301
  - url: /api.*
    script: auto
    secure: always
    redirect_http_response_code: 301
  - url: /(.*\..+)
    static_files: web/build/\1
    upload: web/build/(.*\..+)$
    secure: always
    redirect_http_response_code: 301
  - url: .*
    static_files: build/index.html
    upload: web/build/index.html
    secure: always
    redirect_http_response_code: 301
